routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/cart/set', 'CartController@setCart')->name('cart.set');
Route::get('/cart/calculation', 'Api\CartController@calculationFee')->name('cart.calculation');

Route::group(['middleware' => ['api-lang']], function () {
    Route::get('/roads', 'Api\MapController@roads')->name('roads.get-all');
    Route::get('/notifications', 'Api\NotificationsController@userNotifications')->name('notifications');
    Route::patch('/notifications/mark-read/{id?}', 'Api\NotificationsController@markRead')
        ->name('notifications.mark-read');

    Route::get('/profile/vignettes', 'Api\ProfileController@vignettes')->name('profile.get-vignettes');
    Route::get('/profile/get-signs', 'Api\UserSignController@pagination')->name('profile.get-signs');
    Route::delete('/profile/signs/{id}', 'Api\UserSignController@remove')->name('profile.remove');
    Route::post('/profile/signs', 'Api\UserSignController@store')->name('profile.add-sign');
    Route::post('/profile', 'Api\ProfileController@update')->name('profile.update');

    Route::post('/vignettes/validate', 'ChooseVignetteController@vignettesValidate')->name('vignettes.validate');
    Route::get('/vignettes/check', 'Api\VignetteController@check')->name('vignettes.check');

    Route::post('/cart/add', 'CartController@add')->name('cart.add');
    Route::put('/cart/contacts', 'Api\CartController@updateContacts')->name('order.update');
    Route::get('/cart/data', 'Api\CartController@getCart')->name('cart.items');
    Route::get('/cart/has-items', 'Api\CartController@hasItems')->name('cart.has-items');
    Route::get('/cart/success-order', 'Api\CartController@successOrder')->name('cart.success-order');
    Route::post('/cart/add', 'Api\CartController@add')->name('cart.add');
    Route::delete('/cart/remove/{id}', 'Api\CartController@remove')->name('cart.remove');

    Route::post('/order/store', 'Api\CartController@createOrder')->name('order.store');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::resource('/road', 'RoadController', ['as' => 'admin'])->except(['show']);

    Route::get('/history', 'UserHistoryController@index')->name('admin.history');
    Route::get('/history/{historyId}', 'UserHistoryController@show')->name('admin.history.show');
    Route::get('/history/details/{id}', 'UserHistoryController@details')->name('admin.history.details');
    Route::post('/history/search', 'UserHistoryController@search')->name('admin.history.search');

    Route::get('/vignette', 'VignetteController@index')->name('admin.vignette.index');
    Route::get('/vignette/create', 'VignetteController@create')->name('admin.vignette.create');
});

Route::group(['prefix' => '{lang?}', 'middleware' => ['lang']], function() {
    Route::get('/cart', 'CartController@show')->name('cart.show');

    Route::get('/vignettes', 'ChooseVignetteController@index')->name('vignettes');

    Route::group(['prefix' => 'profile', 'middleware' => ['auth']], function () {
        Route::get('/', 'ProfileController@show')->name('profile.show');
        Route::get('/my-vignettes', 'ProfileController@vignettes')->name('profile.vignettes');
        Route::get('/signs', 'ProfileController@signs')->name('profile.signs');
        Route::get('/notifications', 'ProfileController@notifications')->name('profile.notifications');
    });
});

resources/views/partials/admin/menu.blade.php
@php
    use \App\Services\MenuItem
@endphp

<nav id="sidebar">
    <div class="sidebar-header">
        <h3 class="mb-0"><a href="{{ route('admin.index') }}"> {{ __('E-Tolling') }}</a></h3>

        <button type="button" id="sidebarCollapse" class="sidebar-collapse-btn">
            <i class="fas fa-chevron-left"></i>
        </button>
    </div>

    <ul class="list-unstyled components">
        @userCan('product.index')
        <li class="{{ MenuItem::isActive(route('admin.product.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.product.index') }}">@lang('menu.menu_admin.products')</a>
        </li>
        @endUserCan

        @userCan('order.index')
        <li class="{{ MenuItem::isActive(route('admin.vignette.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.vignette.index') }}">@lang('menu.menu_admin.vignettes')</a>
        </li>
        @endUserCan

        @userCan('category.index')
        <li class="{{ MenuItem::isActive(route('admin.category.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.category.index') }}">@lang('menu.menu_admin.category_products')</a>
        </li>
        @endUserCan

        @userCan('user.index')
        <li class="{{ MenuItem::isActive(route('admin.user.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.user.index') }}">@lang('menu.menu_admin.users')</a>
        </li>
        @endUserCan

        @userCan('user_histories.index')
        <li class="{{ MenuItem::isActive(route('admin.history')) ? 'active' : '' }}">
            <a href="{{ route('admin.history') }}">@lang('menu.menu_admin.visit')</a>
        </li>
        @endUserCan

        @userCan('road.index')
        <li class="{{ MenuItem::isActive(route('admin.road.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.road.index') }}">@lang('menu.menu_admin.road')</a>
        </li>
        @endUserCan

        @userCan('faq.index')
        <li class="{{ MenuItem::isActive(route('admin.faq.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.faq.index') }}">@lang('menu.menu_admin.faq')</a>
        </li>
        @endUserCan

        @userCan('setting.index')
        <li class="{{ MenuItem::isActive(route('admin.setting.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.setting.index') }}">@lang('menu.menu_admin.settings')</a>
        </li>
        @endUserCan

        @userCan('reminder.index')
        <li class="{{ MenuItem::isActive(route('admin.reminder.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.reminder.index') }}">@lang('menu.menu_admin.reminder')</a>
        </li>
        @endUserCan

        @userCan('menu.index')
        <li class="{{ MenuItem::isActive(route('admin.menu.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.menu.index') }}">@lang('menu.menu_admin.menu')</a>
        </li>
        @endUserCan

        @userCan('snippet.index')
        <li class="{{ MenuItem::isActive(route('admin.snippet.index')) ? 'active' : '' }}">
            <a href="{{ route('admin.snippet.index') }}">@lang('menu.menu_admin.snippets')</a>
        </li>
        @endUserCan

        @foreach($packages as $item)
            @userCan($item['menu']['permission'])
            <li class="{{ MenuItem::isActive(route($item['menu']['route'])) ? 'active' : '' }}">
                <a href="{{ route($item['menu']['route']) }}">@lang($item['menu']['title'])</a>
            </li>
            @endUserCan
        @endforeach

        @stack('menu')
    </ul>
</nav>