routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/cart/set', 'CartController@setCart')->name('cart.set');
Route::get('/cart/calculation', 'Api\CartController@calculationFee')->name('cart.calculation');

Route::group(['middleware' => ['api-lang']], function () {
    Route::get('/roads', 'Api\MapController@roads')->name('roads.get-all');
    Route::get('/notifications', 'Api\NotificationsController@userNotifications')->name('notifications');
    Route::patch('/notifications/mark-read/{id?}', 'Api\NotificationsController@markRead')
        ->name('notifications.mark-read');

    Route::get('/profile/vignettes', 'Api\ProfileController@vignettes')->name('profile.get-vignettes');
    Route::get('/profile/get-signs', 'Api\UserSignController@pagination')->name('profile.get-signs');
    Route::delete('/profile/signs/{id}', 'Api\UserSignController@remove')->name('profile.remove');
    Route::post('/profile/signs', 'Api\UserSignController@store')->name('profile.add-sign');
    Route::post('/profile', 'Api\ProfileController@update')->name('profile.update');

    Route::post('/vignettes/validate', 'ChooseVignetteController@vignettesValidate')->name('vignettes.validate');
    Route::get('/vignettes/check', 'Api\VignetteController@check')->name('vignettes.check');

    Route::post('/cart/add', 'CartController@add')->name('cart.add');
    Route::put('/cart/contacts', 'Api\CartController@updateContacts')->name('order.update');
    Route::get('/cart/data', 'Api\CartController@getCart')->name('cart.items');
    Route::get('/cart/has-items', 'Api\CartController@hasItems')->name('cart.has-items');
    Route::get('/cart/success-order', 'Api\CartController@successOrder')->name('cart.success-order');
    Route::post('/cart/add', 'Api\CartController@add')->name('cart.add');
    Route::delete('/cart/remove/{id}', 'Api\CartController@remove')->name('cart.remove');

    Route::post('/order/store', 'Api\CartController@createOrder')->name('order.store');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::resource('/road', 'RoadController', ['as' => 'admin'])->except(['show']);

    Route::get('/history', 'UserHistoryController@index')->name('admin.history');
    Route::get('/history/{historyId}', 'UserHistoryController@show')->name('admin.history.show');
    Route::get('/history/details/{id}', 'UserHistoryController@details')->name('admin.history.details');
    Route::post('/history/search', 'UserHistoryController@search')->name('admin.history.search');

    Route::get('/vignette', 'VignetteController@index')->name('admin.vignette.index');
    Route::get('/vignette/create', 'VignetteController@create')->name('admin.vignette.create');
});

Route::group(['prefix' => '{lang?}', 'middleware' => ['lang']], function() {
    Route::get('/cart', 'CartController@show')->name('cart.show');

    Route::get('/vignettes', 'ChooseVignetteController@index')->name('vignettes');

    Route::group(['prefix' => 'profile', 'middleware' => ['auth']], function () {
        Route::get('/', 'ProfileController@show')->name('profile.show');
        Route::get('/my-vignettes', 'ProfileController@vignettes')->name('profile.vignettes');
        Route::get('/signs', 'ProfileController@signs')->name('profile.signs');
        Route::get('/notifications', 'ProfileController@notifications')->name('profile.notifications');
    });
});

app/Models/Road.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Road extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['number', 'title', 'distance', 'coordinates'];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'coordinates' => 'object'
    ];

    /**
     * The relations to eager load on every query.
     *
     * @var array
     */
    protected $with = ['translate'];

    /**
     * Returns translate of the road.
     *
     * @return HasMany
     */
    public function translate(): HasMany
    {
        return $this->hasMany(RoadTranslate::class)->where('lang', \App::getLocale());
    }

    /**
     * Get all translations for the Road.
     *
     * @return HasMany
     */
    public function translates(): HasMany
    {
        return $this->hasMany(RoadTranslate::class);
    }

    /**
     * Returns the translation for the title
     *
     * @return Attribute
     */
    protected function title(): Attribute
    {
        return Attribute::make(
            get: fn ($value) => $this->translate->first()?->title ?? '',
        );
    }

    /**
     * Returns the desired translation
     *
     * @param $query
     * @param $language
     * @return Model
     */
    public function scopeGetTranslate($query, $language): Model
    {
        return $this->translates()->where('lang', $language)->first();
    }
}

app/Http/Controllers/Admin/RoadController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\RoadRequest;
use App\Models\Road;
use App\Services\Contracts\IRoadService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class RoadController extends Controller
{
    /**
     * Dependency Injection required services
     *
     * @param IRoadService $roadService
     */
    public function __construct(
        protected IRoadService $roadService
    )
    {}

    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index(): View|Factory|Application
    {
        return view('admin.road.index', [
            'roads' => $this->roadService->paginate(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View
     */
    public function create(): View|Factory|Application
    {
        return view('admin.road.create', [
            'languages' => config('app.available_locales', [config('app.fallback_locale')]),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RoadRequest $request
     * @return RedirectResponse
     */
    public function store(RoadRequest $request): RedirectResponse
    {
        try {
            $this->roadService->create($request->validated());
        } catch (\Exception $e) {
            return redirect()->route('admin.road.create')
                ->with('error', $e->getMessage());
        }

        return redirect()->route('admin.road.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Road $road
     * @return Application|Factory|View
     */
    public function edit(Road $road): View|Factory|Application
    {
        return view('admin.road.edit', [
            'road' => $road,
            'languages' => config('app.available_locales', [config('app.fallback_locale')]),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RoadRequest $request
     * @param Road $road
     * @return RedirectResponse
     */
    public function update(RoadRequest $request, Road $road): RedirectResponse
    {
        try {
            $this->roadService->update($road, $request->validated());
        } catch (\Exception $e) {
            return redirect()->route('admin.road.edit', $road)
                ->with('error', $e->getMessage());
        }

        return redirect()->route('admin.road.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Road $road
     * @return RedirectResponse
     */
    public function destroy(Road $road): RedirectResponse
    {
        try {
            $road->delete();
        } catch (\Exception $e) {
            return redirect()->route('admin.road.index', $e->getMessage());
        }

        return redirect()->route('admin.road.index');
    }
}

resources/views/admin/road/create.blade.php
@extends('layouts.admin.app')

@section('content')

    <div class="container">
        <form
            class="form-horizontal"
            action="{{route('admin.road.store')}}"
            method="post"
            enctype="multipart/form-data"
        >
            @csrf

            @include('admin.road.partials.form')

            <hr/>

            <a href="{{ route('admin.road.index') }}" class="btn btn-default">
                {{ trans('common.cancel') }}
            </a>

            <input
                type="submit"
                class="btn btn-primary"
                value="{{ trans('common.save') }}"
            />
        </form>
    </div>

@endsection

resources/views/admin/road/edit.blade.php
@extends('layouts.admin.app')

@section('content')

    <div class="container">

        @if(!empty($road->coordinates))
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <div id="map" class="map"></div>
                </div>
            </div>
        @endif

        <form
            class="form-horizontal"
            action="{{route('admin.road.update', $road)}}"
            method="post"
            enctype="multipart/form-data"
        >
            @csrf

            @method('PATCH')

            @include('admin.road.partials.form', ['road' => $road])

            <hr/>

            <a href="{{ route('admin.road.index') }}" class="btn btn-default">
                {{ trans('common.cancel') }}
            </a>

            <input type="submit" class="btn btn-primary" value="{{ trans('common.save') }}">
        </form>
    </div>

@endsection

@if(!empty($road->coordinates))
    @push('scripts')
        @include('test-example.partials.map-script', ['roads' => collect([$road])])
    @endpush
@endif

resources/views/admin/road/index.blade.php
@extends('layouts.admin.app')

@section('title')
    {{ trans('road.pageTitle') }}
@endsection

@section('content')

    <div class="container">
        @userCan('product.create')
            <a href="{{route('admin.road.create')}}" class="btn btn-primary pull-right">
                <i class="fas fa-plus"></i> {{ trans('common.create') }}
            </a>
        @endUserCan

        <table class="table table-stripped" aria-describedby="Categories table">
            <thead>
                <tr>
                    <th>
                        {{ trans('road.id') }}
                    </th>
                    <th>
                        {{ trans('road.number') }}
                    </th>
                    <th>
                        {{ trans('road.title') }}
                    </th>
                    <th>
                        {{ trans('road.distance') }}
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            @forelse($roads as $road)
                <tr>
                    <td>{{ $road->id }}</td>
                    <td>{{ $road->number }}</td>
                    <td>{{ $road->title }}</td>
                    <td>{{ $road->distance }}</td>
                    <td class="text-right">
                        @userCan('road.update')
                            <a
                                href="{{ route('admin.road.edit', $road) }}"
                                class="btn btn-default d-inline-block"
                                title="{{ trans('common.edit') }}"
                            >
                                <i class="fas fa-edit"></i>
                            </a>
                        @endUserCan

                        @userCan('road.delete')
                            <form
                                onsubmit="if(confirm('Delete?')) { return true;} else { return false; }"
                                action="{{ route('admin.road.destroy', $road) }}"
                                method="post"
                                class="d-inline-block"
                            >
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-default" type="submit" title="{{ trans('common.delete') }}">
                                    <i class="fas fa-trash-alt"></i>
                                </button>
                            </form>
                        @endUserCan
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="5" class="text-center">
                        <h2>{{ trans('common.no_data') }}</h2>
                    </td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="5">
                    {{ $roads->links() }}
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

@endsection